export const MODALS = {
    CANCELLATION_CONFIRMATION: "CANCELLATION_CONFIRMATION",
    SEND_INVOICE: "SEND_INVOICE",
    SEARCH_OVERLOAD: "SEARCH_OVERLOAD",
    REPORT_DUPLICATE: "REPORT_DUPLICATE",
    READ_ONLY: "READ_ONLY"
};
